import { Listing, User, Condition, Category, AgeRange, Charity, TrustTier } from './types';
import { ZIP_COORDINATES } from './utils/locationHelpers';

// Default charity for MVP - hardcoded single partner
export const DEFAULT_CHARITY: Charity = {
  id: 'charity-auburn-food-bank',
  name: 'Auburn Food Bank',
  shortDescription: 'Kids Backpack Program - weekend meals for local students',
  fullDescription: 'The Auburn Food Bank serves families in need throughout the Auburn area. Their Kids Backpack Program provides weekend food packs to students who rely on school meals during the week.',
  websiteUrl: 'https://auburnfoodbank.org',
  logoUrl: '', // Add when available
  locationCity: 'Auburn',
  locationState: 'WA',
  isActive: true,
  totalReceived: 0,
  createdAt: new Date().toISOString(),
};

export const CURRENT_USER: User = {
  id: 'u1',
  name: 'Sarah M.',
  isVerifiedParent: true,
  joinDate: 'Jan 2024',
  itemsSold: 12,
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  location: 'Auburn, WA',
  bio: 'Mom of 2. Clearing out the garage!',
  // Trust & Verification
  trustTier: TrustTier.TRUSTED,
  phoneVerified: true,
  emailVerified: true,
  hasPaymentMethod: true,
  hasProfilePhoto: true,
  socialGoogleConnected: true,
  idVerified: true,
  idVerifiedAt: '2024-01-15T00:00:00Z',
  completedTransactions: 8,
  averageRating: 4.9,
  responseTimeHours: 2.5
};

export const MOCK_USERS: Record<string, User> = {
  'u2': {
    id: 'u2',
    name: 'Jessica R.',
    isVerifiedParent: true,
    joinDate: 'Dec 2023',
    itemsSold: 5,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    location: 'Auburn, WA',
    bio: 'Safety first! All items sanitized before pickup.',
    trustTier: TrustTier.TRUSTED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    socialFacebookConnected: true,
    idVerified: true,
    completedTransactions: 5,
    averageRating: 4.8,
    responseTimeHours: 1.5
  },
  'u3': {
    id: 'u3',
    name: 'Mike T.',
    isVerifiedParent: false,
    joinDate: 'Feb 2024',
    itemsSold: 1,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    location: 'Federal Way, WA',
    bio: 'Dad to a new toddler.',
    trustTier: TrustTier.BASIC,
    phoneVerified: true,
    emailVerified: false,
    hasProfilePhoto: true
  },
  'u4': {
    id: 'u4',
    name: 'Emily W.',
    isVerifiedParent: true,
    joinDate: 'Nov 2023',
    itemsSold: 22,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    location: 'Lakeland Hills, WA',
    bio: 'Selling gently used clothes and toys.',
    trustTier: TrustTier.TRUSTED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    socialGoogleConnected: true,
    idVerified: false,
    completedTransactions: 22,
    averageRating: 4.7,
    responseTimeHours: 3.2
  },
  'u5': {
    id: 'u5',
    name: 'Ashley K.',
    isVerifiedParent: true,
    joinDate: 'Mar 2024',
    itemsSold: 0,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashley',
    location: 'Auburn, WA',
    bio: 'New to the neighborhood.',
    trustTier: TrustTier.VERIFIED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    socialAppleConnected: true,
    idVerified: false,
    completedTransactions: 0
  },
  'u6': {
    id: 'u6',
    name: 'Rachel M.',
    isVerifiedParent: true,
    joinDate: 'Oct 2023',
    itemsSold: 15,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
    location: 'Kent, WA',
    bio: 'Twin mom clearing out! Everything must go.',
    trustTier: TrustTier.TRUSTED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    idVerified: true,
    completedTransactions: 15,
    averageRating: 4.9,
    responseTimeHours: 1.0
  },
  'u7': {
    id: 'u7',
    name: 'David L.',
    isVerifiedParent: true,
    joinDate: 'Jan 2024',
    itemsSold: 8,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    location: 'Renton, WA',
    bio: 'Stay-at-home dad. Quick responses!',
    trustTier: TrustTier.VERIFIED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    socialGoogleConnected: true,
    completedTransactions: 8,
    averageRating: 4.6,
    responseTimeHours: 0.5
  },
  'u8': {
    id: 'u8',
    name: 'Amanda S.',
    isVerifiedParent: true,
    joinDate: 'Sep 2023',
    itemsSold: 31,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    location: 'Puyallup, WA',
    bio: 'Professional organizer. All items in pristine condition.',
    trustTier: TrustTier.TRUSTED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    idVerified: true,
    completedTransactions: 31,
    averageRating: 5.0,
    responseTimeHours: 2.0
  },
  'u9': {
    id: 'u9',
    name: 'Chris P.',
    isVerifiedParent: false,
    joinDate: 'Apr 2024',
    itemsSold: 2,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris',
    location: 'Tacoma, WA',
    bio: 'First-time dad learning as I go!',
    trustTier: TrustTier.BASIC,
    phoneVerified: true,
    hasProfilePhoto: true
  },
  'u10': {
    id: 'u10',
    name: 'Lisa H.',
    isVerifiedParent: true,
    joinDate: 'Dec 2023',
    itemsSold: 11,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    location: 'Federal Way, WA',
    bio: 'Mom of 3. Lots of great stuff to pass along!',
    trustTier: TrustTier.TRUSTED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    socialFacebookConnected: true,
    idVerified: true,
    completedTransactions: 11,
    averageRating: 4.7,
    responseTimeHours: 4.0
  },
  'u11': {
    id: 'u11',
    name: 'Jennifer B.',
    isVerifiedParent: true,
    joinDate: 'Feb 2024',
    itemsSold: 6,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer',
    location: 'Auburn, WA',
    bio: 'Expecting #2! Upgrading everything.',
    trustTier: TrustTier.VERIFIED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    completedTransactions: 6,
    averageRating: 4.8
  },
  'u12': {
    id: 'u12',
    name: 'Marcus J.',
    isVerifiedParent: true,
    joinDate: 'Nov 2023',
    itemsSold: 4,
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    location: 'Kent, WA',
    bio: 'Quality over quantity. Only the best for our little one.',
    trustTier: TrustTier.VERIFIED,
    phoneVerified: true,
    emailVerified: true,
    hasPaymentMethod: true,
    hasProfilePhoto: true,
    socialAppleConnected: true,
    completedTransactions: 4,
    averageRating: 4.9
  }
};

export const MOCK_LISTINGS: Listing[] = [
  // GEAR
  {
    id: 'l1',
    userId: 'u2',
    title: 'UPPAbaby Vista V2 Stroller',
    description: 'Gently used stroller in Jake (Black/Carbon). Includes bassinet and toddler seat. Always stored indoors. Smoke-free home.',
    price: 650,
    originalPrice: 999,
    condition: Condition.EXCELLENT,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'UPPAbaby',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '2 hours ago'
  },
  {
    id: 'l3',
    userId: 'u4',
    title: 'Ergobaby Omni 360 Carrier',
    description: 'Mesh carrier, very breathable. Perfect for hiking. Washed and ready to go.',
    price: 80,
    originalPrice: 180,
    condition: Condition.GOOD,
    category: Category.GEAR,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Ergobaby',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98092',
    coordinates: ZIP_COORDINATES['98092'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '3 days ago'
  },
  {
    id: 'l5',
    userId: 'u6',
    title: 'Bugaboo Fox 3 Complete',
    description: 'Beautiful stroller in Forest Green. Used for one child only. Includes rain cover, cup holder, and car seat adapters.',
    price: 799,
    originalPrice: 1299,
    condition: Condition.EXCELLENT,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Bugaboo',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '5 hours ago'
  },
  {
    id: 'l6',
    userId: 'u7',
    title: 'Baby Jogger City Mini GT2',
    description: 'All-terrain stroller in Jet. One-hand quick fold. Great for jogging or rough sidewalks.',
    price: 275,
    originalPrice: 450,
    condition: Condition.VERY_GOOD,
    category: Category.GEAR,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Baby Jogger',
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98057',
    coordinates: ZIP_COORDINATES['98057'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l7',
    userId: 'u8',
    title: 'Nuna PIPA Lite RX Car Seat',
    description: 'Ultra-lightweight infant car seat (only 5.3 lbs!). Expires 2027. Dream drape included.',
    price: 225,
    originalPrice: 450,
    condition: Condition.EXCELLENT,
    category: Category.SAFETY,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Nuna',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98371',
    coordinates: ZIP_COORDINATES['98371'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '6 hours ago'
  },
  {
    id: 'l8',
    userId: 'u10',
    title: 'Graco 4Ever DLX Car Seat',
    description: '4-in-1 convertible car seat. Used by one child, never in an accident. Expires 2029.',
    price: 175,
    originalPrice: 350,
    condition: Condition.VERY_GOOD,
    category: Category.SAFETY,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Graco',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98003',
    coordinates: ZIP_COORDINATES['98003'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '2 days ago'
  },
  // TOYS
  {
    id: 'l2',
    userId: 'u3',
    title: 'Wooden Activity Gym',
    description: 'Minimalist wooden play gym. Great condition, just a few scuffs on the bottom.',
    price: 45,
    originalPrice: 80,
    condition: Condition.VERY_GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Lovevery',
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98002',
    coordinates: ZIP_COORDINATES['98002'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l9',
    userId: 'u4',
    title: 'Lovevery Play Kits (3 boxes)',
    description: 'The Inspector, Explorer, and Pioneer kits. All pieces included. Age 7-12 months.',
    price: 95,
    originalPrice: 240,
    condition: Condition.VERY_GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Lovevery',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98092',
    coordinates: ZIP_COORDINATES['98092'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '12 hours ago'
  },
  {
    id: 'l10',
    userId: 'u6',
    title: 'LEGO DUPLO Mega Set',
    description: 'Over 200 pieces! Includes train, farm animals, and building plates. Perfect for creative play.',
    price: 55,
    originalPrice: 150,
    condition: Condition.GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.TWO_TO_THREE_YR,
    brand: 'LEGO',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '3 days ago'
  },
  {
    id: 'l11',
    userId: 'u9',
    title: 'Fisher-Price Laugh & Learn Walker',
    description: 'Musical learning walker with lights and sounds. All buttons work perfectly.',
    price: 15,
    originalPrice: 35,
    condition: Condition.GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Fisher-Price',
    isSmokeFree: false,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98405',
    coordinates: ZIP_COORDINATES['98405'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '4 days ago'
  },
  {
    id: 'l12',
    userId: 'u11',
    title: 'Melissa & Doug Wooden Puzzles (Set of 8)',
    description: 'Various animal and vehicle puzzles. Great for toddlers learning shapes.',
    price: 25,
    originalPrice: 60,
    condition: Condition.VERY_GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.TWELVE_TO_EIGHTEEN_MO,
    brand: 'Melissa & Doug',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1596073419667-9d77d59f033f?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '8 hours ago'
  },
  // CLOTHING
  {
    id: 'l4',
    userId: 'u5',
    title: 'Huge Lot of 2T Boy Clothes',
    description: 'Over 20 items. Gap, Old Navy, Carter\'s. Pants, shirts, and pajamas.',
    price: 30,
    condition: Condition.GOOD,
    category: Category.CLOTHING,
    ageRange: AgeRange.TWO_TO_THREE_YR,
    isSmokeFree: false,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '4 hours ago'
  },
  {
    id: 'l13',
    userId: 'u8',
    title: 'Hanna Andersson Pajamas (5 sets)',
    description: 'Organic cotton PJs in size 80 (18-24mo). Stripes and solids. Washed in fragrance-free detergent.',
    price: 45,
    originalPrice: 150,
    condition: Condition.EXCELLENT,
    category: Category.CLOTHING,
    ageRange: AgeRange.EIGHTEEN_TO_TWENTY_FOUR_MO,
    brand: 'Hanna Andersson',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98371',
    coordinates: ZIP_COORDINATES['98371'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l14',
    userId: 'u10',
    title: 'Primary.com Basics Bundle (NB-3M)',
    description: '12 solid color onesies, perfect for mixing and matching. Gender neutral colors.',
    price: 35,
    originalPrice: 96,
    condition: Condition.VERY_GOOD,
    category: Category.CLOTHING,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Primary',
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98003',
    coordinates: ZIP_COORDINATES['98003'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '5 days ago'
  },
  {
    id: 'l15',
    userId: 'u12',
    title: 'Patagonia Baby Down Sweater',
    description: 'Size 12-18mo in Passage Blue. Like new - only worn a few times.',
    price: 50,
    originalPrice: 99,
    condition: Condition.LIKE_NEW,
    category: Category.CLOTHING,
    ageRange: AgeRange.TWELVE_TO_EIGHTEEN_MO,
    brand: 'Patagonia',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '2 days ago'
  },
  {
    id: 'l16',
    userId: 'u7',
    title: 'Girls Dress Bundle (3T)',
    description: '8 dresses perfect for summer. Tea Collection, Boden, and Cat & Jack.',
    price: 40,
    condition: Condition.GOOD,
    category: Category.CLOTHING,
    ageRange: AgeRange.THREE_TO_FIVE_YR,
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98057',
    coordinates: ZIP_COORDINATES['98057'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '3 days ago'
  },
  // FURNITURE (using CRIBS category)
  {
    id: 'l17',
    userId: 'u2',
    title: 'Babyletto Hudson Crib (White)',
    description: 'Beautiful 3-in-1 convertible crib. Converts to toddler bed and daybed. Mattress not included.',
    price: 250,
    originalPrice: 400,
    condition: Condition.VERY_GOOD,
    category: Category.CRIBS,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Babyletto',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l18',
    userId: 'u8',
    title: 'Pottery Barn Kids Rocking Chair',
    description: 'Personalized with "Emma" - can be slipcovered. White wood frame.',
    price: 75,
    originalPrice: 199,
    condition: Condition.GOOD,
    category: Category.GEAR,
    ageRange: AgeRange.TWO_TO_THREE_YR,
    brand: 'Pottery Barn Kids',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98371',
    coordinates: ZIP_COORDINATES['98371'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '4 days ago'
  },
  {
    id: 'l19',
    userId: 'u6',
    title: 'IKEA Sniglar Changing Table',
    description: 'Solid beech wood changing table. Super sturdy. Includes pad.',
    price: 45,
    originalPrice: 80,
    condition: Condition.VERY_GOOD,
    category: Category.CRIBS,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'IKEA',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '2 days ago'
  },
  {
    id: 'l20',
    userId: 'u11',
    title: 'Stokke Tripp Trapp High Chair',
    description: 'Classic Tripp Trapp in Walnut. Grows with your child. Baby set included.',
    price: 175,
    originalPrice: 350,
    condition: Condition.VERY_GOOD,
    category: Category.FEEDING,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Stokke',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '6 hours ago'
  },
  // FEEDING
  {
    id: 'l21',
    userId: 'u4',
    title: 'Spectra S1 Breast Pump',
    description: 'Hospital-grade pump with rechargeable battery. Includes extra flanges (24mm & 28mm).',
    price: 125,
    originalPrice: 230,
    condition: Condition.VERY_GOOD,
    category: Category.FEEDING,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Spectra',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98092',
    coordinates: ZIP_COORDINATES['98092'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '3 hours ago'
  },
  {
    id: 'l22',
    userId: 'u10',
    title: 'Baby Brezza Formula Pro Advanced',
    description: 'Makes bottles instantly! Like having a Keurig for formula. Just cleaned and descaled.',
    price: 95,
    originalPrice: 200,
    condition: Condition.GOOD,
    category: Category.FEEDING,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Baby Brezza',
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98003',
    coordinates: ZIP_COORDINATES['98003'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '2 days ago'
  },
  {
    id: 'l23',
    userId: 'u12',
    title: 'OXO Tot Sprout High Chair',
    description: 'Modern design high chair. Easy to clean with removable tray.',
    price: 150,
    originalPrice: 250,
    condition: Condition.EXCELLENT,
    category: Category.FEEDING,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'OXO',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l24',
    userId: 'u9',
    title: 'Dr. Brown\'s Bottle Set (New)',
    description: 'Unopened 8-pack of anti-colic bottles. Various sizes. We switched to Comotomo.',
    price: 25,
    originalPrice: 45,
    condition: Condition.LIKE_NEW,
    category: Category.FEEDING,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Dr. Brown\'s',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98405',
    coordinates: ZIP_COORDINATES['98405'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '5 hours ago'
  },
  // BOOKS (using TOYS category which includes books)
  {
    id: 'l25',
    userId: 'u7',
    title: 'Board Book Collection (25 books)',
    description: 'Eric Carle, Sandra Boynton, and more! Perfect starter library.',
    price: 35,
    condition: Condition.GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98057',
    coordinates: ZIP_COORDINATES['98057'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '2 days ago'
  },
  {
    id: 'l26',
    userId: 'u8',
    title: 'Usborne Lift-the-Flap Books (12)',
    description: 'Educational lift-the-flap books. Numbers, colors, animals, and more.',
    price: 40,
    originalPrice: 120,
    condition: Condition.VERY_GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.TWELVE_TO_EIGHTEEN_MO,
    brand: 'Usborne',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98371',
    coordinates: ZIP_COORDINATES['98371'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '4 days ago'
  },
  // MORE GEAR
  {
    id: 'l27',
    userId: 'u3',
    title: '4moms MamaRoo Swing',
    description: '5 unique motions. Bluetooth enabled. Grey Classic. Works perfectly!',
    price: 100,
    originalPrice: 250,
    condition: Condition.GOOD,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: '4moms',
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98002',
    coordinates: ZIP_COORDINATES['98002'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l28',
    userId: 'u5',
    title: 'Snoo Smart Bassinet',
    description: 'THE sleep training bassinet. Responds to crying with motion and sound. Includes extra sheets.',
    price: 800,
    originalPrice: 1695,
    condition: Condition.EXCELLENT,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Happiest Baby',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '7 hours ago'
  },
  {
    id: 'l29',
    userId: 'u11',
    title: 'Pack n Play with Bassinet',
    description: 'Graco Pack n Play with newborn napper. Folds compact for travel.',
    price: 65,
    originalPrice: 150,
    condition: Condition.GOOD,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Graco',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: true,
    distanceMiles: 0,
    createdAt: '3 days ago'
  },
  {
    id: 'l30',
    userId: 'u6',
    title: 'Baby Bjorn Bouncer Bliss',
    description: 'Mesh fabric bouncer in Anthracite. No batteries needed - baby powers the bounce!',
    price: 120,
    originalPrice: 230,
    condition: Condition.LIKE_NEW,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'BabyBjorn',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '8 hours ago'
  },
  // SAFETY
  {
    id: 'l31',
    userId: 'u2',
    title: 'Nanit Pro Baby Monitor',
    description: 'Smart HD monitor with sleep tracking. Wall mount and floor stand included.',
    price: 175,
    originalPrice: 350,
    condition: Condition.VERY_GOOD,
    category: Category.SAFETY,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Nanit',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98001',
    coordinates: ZIP_COORDINATES['98001'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '2 days ago'
  },
  {
    id: 'l32',
    userId: 'u10',
    title: 'Baby Gates (2) - Pressure Mount',
    description: 'Regalo Easy Step Walk Through gates. 29-39" wide. Perfect for doorways.',
    price: 30,
    originalPrice: 80,
    condition: Condition.GOOD,
    category: Category.SAFETY,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Regalo',
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1596073419667-9d77d59f033f?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98003',
    coordinates: ZIP_COORDINATES['98003'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '5 days ago'
  },
  // OTHER / SEASONAL (using CLOTHING for costumes)
  {
    id: 'l33',
    userId: 'u7',
    title: 'Halloween Costumes (12-24mo)',
    description: 'Dragon, pumpkin, and lion costumes. All in great shape.',
    price: 20,
    condition: Condition.GOOD,
    category: Category.CLOTHING,
    ageRange: AgeRange.TWELVE_TO_EIGHTEEN_MO,
    isSmokeFree: true,
    isPetFree: false,
    images: ['https://images.unsplash.com/photo-1509557965875-b88c97052f0e?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98057',
    coordinates: ZIP_COORDINATES['98057'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '6 days ago'
  },
  {
    id: 'l34',
    userId: 'u12',
    title: 'Summer Infant Baby Bathtub',
    description: 'Comfort height bathing tub with sling. Grows with baby from newborn to toddler.',
    price: 15,
    originalPrice: 35,
    condition: Condition.GOOD,
    category: Category.GEAR,
    ageRange: AgeRange.ZERO_TO_SIX_MO,
    brand: 'Summer Infant',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98032',
    coordinates: ZIP_COORDINATES['98032'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '1 day ago'
  },
  {
    id: 'l35',
    userId: 'u4',
    title: 'Skip Hop Activity Center',
    description: '360° activity center with 3 stages. Keeps baby entertained while you cook!',
    price: 55,
    originalPrice: 130,
    condition: Condition.VERY_GOOD,
    category: Category.TOYS,
    ageRange: AgeRange.SIX_TO_TWELVE_MO,
    brand: 'Skip Hop',
    isSmokeFree: true,
    isPetFree: true,
    images: ['https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&q=80&w=800'],
    locationZip: '98092',
    coordinates: ZIP_COORDINATES['98092'],
    isSafetyVerified: false,
    distanceMiles: 0,
    createdAt: '4 hours ago'
  }
];